// Mocks generated by Mockito 5.0.17 from annotations
// in todo_flutter_to_practice/test/app_runner_test.dart.
// Do not manually edit this file.

import 'package:flutter/cupertino.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

import 'app_runner_test.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [RunAppFunction].
///
/// See the documentation for Mockito's code generation for more information.
class MockRunAppFunction extends _i1.Mock implements _i2.RunAppFunction {
  MockRunAppFunction() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void call(_i3.Widget? widget) =>
      super.noSuchMethod(Invocation.method(#call, [widget]),
          returnValueForMissingStub: null);
}
