// Mocks generated by Mockito 5.2.0 from annotations
// in todo_flutter_to_practice/test/widget_tests/password_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

import 'password_test.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [SignInWithEmailAndPasswordFunction].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInWithEmailAndPasswordFunction extends _i1.Mock
    implements _i2.SignInWithEmailAndPasswordFunction {
  MockSignInWithEmailAndPasswordFunction() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(String? email, String? password,
          void Function(_i4.FirebaseAuthException)? errorCallback) =>
      (super.noSuchMethod(
          Invocation.method(#call, [email, password, errorCallback]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
}
